# Generated by rust2rpm 11
%bcond_without check
%global debug_package %{nil}

%global crate ffsend-api

Name:           rust-%{crate}
Version:        0.4.4
Release:        2%{?dist}
Summary:        Fully featured Firefox Send API client

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/ffsend-api
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Fully featured Firefox Send API client.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+send2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+send2-devel %{_description}

This package contains library source intended for building other packages
which use "send2" feature of "%{crate}" crate.

%files       -n %{name}+send2-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+send3-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+send3-devel %{_description}

This package contains library source intended for building other packages
which use "send3" feature of "%{crate}" crate.

%files       -n %{name}+send3-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+websocket-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+websocket-devel %{_description}

This package contains library source intended for building other packages
which use "websocket" feature of "%{crate}" crate.

%files       -n %{name}+websocket-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.4.4-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Thu Dec 05 15:30:21 CET 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.4.4-1
- Update to 0.4.4

* Thu Dec 05 14:35:26 CET 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.4.1-1
- Update to 0.4.1

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.3.2-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Sat Jun 22 13:06:05 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.3.2-3
- Regenerate

* Fri Apr 19 09:20:28 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.3.2-2
- Update version-compare to 0.0.8

* Fri Apr 05 17:23:05 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.3.2-1
- Update to 0.3.2

* Wed Mar 20 2019 Josh Stone <jistone@redhat.com> - 0.3.0-1
- Update to 0.3.0

* Wed Mar 13 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.2.3-1
- Initial package
